services:

  auth-service:
    build:
      context: backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    expose:
      - 8080
    depends_on:
      - auth-db
      - auth-liquibase
    env_file:
      .env
    restart: no
    networks:
      - auth-network

  auth-db:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: ${AUTH_SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${AUTH_SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  auth-liquibase:
    image: liquibase/liquibase:4.29
    container_name: auth-liquibase
    depends_on:
      - auth-db
    volumes:
      - ./auth-service/migrations:/changesets
    command:
      - --searchPath=${AUTH_LIQUIBASE_SEARCH_PATH}
      - --changelog-file=${AUTH_LIQUIBASE_CHANGELOG_FILE}
      - --driver=${AUTH_LIQUIBASE_DRIVER}
      - --url=${AUTH_LIQUIBASE_URL}
      - --username=${AUTH_LIQUIBASE_USERNAME}
      - --password=${AUTH_LIQUIBASE_PASSWORD}
      - update
    networks:
      - auth-network

volumes:
  auth-db-data:

networks:
  auth-network:

