spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
          filters:
            - StripPrefix=1

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - StripPrefix=1

server:
  port: 8080
